services:
  - type: web
    name: huapi-war
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 10000
